events { 
    worker_connections 1024; 
}

http {
    include /etc/nginx/mime.types;
    
    server {
        listen 80;
        server_name localhost;

        # 1. Servir la página web estática
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # 2. El puente directo al contenedor backend-api
        location /api/ {
            proxy_pass http://backend-api:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}